# Generated by Django 5.0.6 on 2024-06-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='1708190589974.jpg', upload_to='module/'),
        ),
    ]
